---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-frontend
  labels:
    app: zabbix-frontend
spec:
  replicas: 1  # Este componente es stateless, así que se puede escalar
  selector:
    matchLabels:
      app: zabbix-frontend
  template:
    metadata:
      labels:
        app: zabbix-frontend
    spec:
      containers:
      - name: zabbix-frontend
        image: zabbix/zabbix-web-nginx-pgsql:7.4
        env:
          - name: DB_SERVER_HOST
            value: "zabbix-postgres"
          - name: POSTGRES_DB
            value: "zabbix"
          - name: POSTGRES_USER
            value: "zabbix"
          - name: POSTGRES_PASSWORD
            value: "zabbix_password"
          - name: ZBX_SERVER_HOST
            value: "zabbix-server"
          - name: PHP_TZ
            value: "Europe/Madrid"  # Ajusta según tu zona horaria
        ports:
          - containerPort: 8080
            name: http
