---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-frontend
  labels:
    app: zabbix-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: zabbix-frontend

