---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix-server
spec:
  replicas: 1   # Zabbix server suele ejecutarse en modo activo-standby para evitar problemas de concurrencia
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:7.5
        env:
          - name: DB_SERVER_HOST
            value: "zabbix-postgres"
          - name: POSTGRES_DB
            value: "zabbix"
          - name: POSTGRES_USER
            value: "zabbix"
          - name: POSTGRES_PASSWORD
            value: "zabbix_password"
        ports:
          - containerPort: 10051
            name: zabbix-server
