---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  labels:
    app: zabbix-server
spec:
  ports:
    - port: 10051
      targetPort: 10051
      name: zabbix-server
  selector:
    app: zabbix-server
